#include "core/generation.h"
#include "ops/cpu/embedding_cpu.h"
#include "ops/cpu/linear_cpu.h"
#include "ops/cpu/rmsnorm_cpu.h"
#include "ops/cpu/rope_cpu.h"
#include "ops/cpu/attention_cpu.h"
#include "ops/cpu/swiglu_cpu.h"

#include <algorithm>
#include <cmath>
#include <cstring>
#include <cstdint>
#include <random>
#include <stdexcept>

namespace {
float read(const Tensor& t,std::size_t i){std::vector<float> x(t.numel());t.copy_to_host(x);return x[i];}
void copy_tensor(Tensor& dst,const Tensor& src){std::memcpy(dst.raw_data(),src.raw_data(),src.nbytes());}
void add(Tensor& a,const Tensor& b){auto* d=static_cast<std::uint8_t*>(a.raw_data());const auto* s=static_cast<const std::uint8_t*>(b.raw_data());for(std::size_t i=0;i<a.numel();++i){if(a.dtype()==Dtype::F32)static_cast<float*>(a.raw_data())[i]+=static_cast<const float*>(b.raw_data())[i];else {std::vector<float> av(a.numel()),bv(b.numel());a.copy_to_host(av);b.copy_to_host(bv);for(std::size_t j=0;j<a.numel();++j)av[j]+=bv[j];a.copy_from_host(av);break;}}static_cast<void>(d);static_cast<void>(s);}
bpe::TokenId sample(const std::vector<float>& logits,const std::vector<bpe::TokenId>& ctx,const GenerationOptions& o,std::mt19937_64& rng){std::vector<float> x=logits;std::vector<std::size_t> count(x.size());for(auto id:ctx)if(id<x.size())++count[id];for(std::size_t i=0;i<x.size();++i)if(count[i]){x[i]=x[i]>=0?x[i]/o.repetition_penalty:x[i]*o.repetition_penalty;x[i]-=o.presence_penalty+o.frequency_penalty*float(count[i]);}std::vector<std::size_t> ids(x.size());for(std::size_t i=0;i<x.size();++i)ids[i]=i;std::sort(ids.begin(),ids.end(),[&](auto a,auto b){return x[a]>x[b];});if(o.top_k&&o.top_k<ids.size())ids.resize(o.top_k);if(o.temperature==0)return static_cast<bpe::TokenId>(ids.front());float mx=x[ids.front()],sum=0;std::vector<float> p(ids.size());for(std::size_t i=0;i<ids.size();++i){p[i]=std::exp((x[ids[i]]-mx)/o.temperature);sum+=p[i];}for(auto& v:p)v/=sum;if(o.top_p<1){float c=0;std::size_t n=p.size();for(std::size_t i=0;i<p.size();++i){c+=p[i];if(c>=o.top_p){n=i+1;break;}}ids.resize(n);p.resize(n);float z=0;for(auto v:p)z+=v;for(auto& v:p)v/=z;}std::discrete_distribution<std::size_t>d(p.begin(),p.end());return static_cast<bpe::TokenId>(ids[d(rng)]);}
void forward(Tensor& logits,const std::vector<bpe::TokenId>& ids,const TransformerModelWeights& w,const TransformerModelOptions& o,const Tensor& co,const Tensor& si){const auto S=ids.size(),H=o.block_options.hidden_size,Q=o.block_options.num_query_heads,KV=o.block_options.num_kv_heads,D=o.block_options.head_dim,I=o.block_options.intermediate_size;Tensor h({S,H},w.token_embedding.dtype(),DeviceType::CPU);embedding_forward_cpu(h,ids.data(),S,w.token_embedding);for(const auto& l:w.layers){Tensor n({S,H},h.dtype(),DeviceType::CPU);rmsnorm_forward_cpu(n,h,l.attention_norm,o.block_options.rms_epsilon);Tensor qf({S,Q*D},h.dtype(),DeviceType::CPU),kf({S,KV*D},h.dtype(),DeviceType::CPU),vf({S,KV*D},h.dtype(),DeviceType::CPU);linear_forward_cpu(qf,n,l.q_projection);linear_forward_cpu(kf,n,l.k_projection);linear_forward_cpu(vf,n,l.v_projection);Tensor qn({S*Q,D},h.dtype(),DeviceType::CPU),kn({S*KV,D},h.dtype(),DeviceType::CPU);copy_tensor(qn,qf);copy_tensor(kn,kf);Tensor qnw({D},h.dtype(),DeviceType::CPU),knw({D},h.dtype(),DeviceType::CPU);copy_tensor(qnw,l.q_norm);copy_tensor(knw,l.k_norm);Tensor qno(qn.shape(),h.dtype(),DeviceType::CPU),kno(kn.shape(),h.dtype(),DeviceType::CPU);rmsnorm_forward_cpu(qno,qn,qnw,o.block_options.rms_epsilon);rmsnorm_forward_cpu(kno,kn,knw,o.block_options.rms_epsilon);copy_tensor(qf,qno);copy_tensor(kf,kno);Tensor q({1,S,Q,D},h.dtype(),DeviceType::CPU),k({1,S,KV,D},h.dtype(),DeviceType::CPU),v({1,S,KV,D},h.dtype(),DeviceType::CPU);copy_tensor(q,qf);copy_tensor(k,kf);copy_tensor(v,vf);RopeOptions ro{o.block_options.rotary_dim,0};rope_forward_cpu(q,k,co,si,ro);Tensor ao({1,S,Q,D},h.dtype(),DeviceType::CPU);FlashAttentionOptions aoopt{Q,KV,D,0,o.block_options.causal};flash_gqa_attention_forward_cpu(ao,q,k,v,aoopt);Tensor af({S,H},h.dtype(),DeviceType::CPU);copy_tensor(af,ao);Tensor proj({S,H},h.dtype(),DeviceType::CPU);linear_forward_cpu(proj,af,l.o_projection);add(h,proj);Tensor fn({S,H},h.dtype(),DeviceType::CPU);rmsnorm_forward_cpu(fn,h,l.ffn_norm,o.block_options.rms_epsilon);Tensor gate({S,I},h.dtype(),DeviceType::CPU),up({S,I},h.dtype(),DeviceType::CPU);linear_forward_cpu(gate,fn,l.gate_proj);linear_forward_cpu(up,fn,l.up_proj);Tensor act({S,I},h.dtype(),DeviceType::CPU);swiglu_forward_cpu(act,gate,up);Tensor down({S,H},h.dtype(),DeviceType::CPU);linear_forward_cpu(down,act,l.down_proj);add(h,down);}Tensor norm({S,H},h.dtype(),DeviceType::CPU);rmsnorm_forward_cpu(norm,h,w.final_norm,o.block_options.rms_epsilon);linear_forward_cpu(logits,norm,w.lm_head);}
}
std::vector<bpe::TokenId> generate_tokens_cpu(const std::vector<bpe::TokenId>& prompt,const TransformerModelWeights& w,const Tensor& co,const Tensor& si,const TransformerModelOptions& o,const GenerationOptions& go){if(prompt.empty())throw std::invalid_argument("prompt must contain at least one token");if(!go.max_new_tokens)return prompt;if(!go.max_context_tokens)throw std::invalid_argument("max_context_tokens must be positive");std::mt19937_64 rng(go.seed?go.seed:std::random_device{}());std::vector<bpe::TokenId> result=prompt;for(std::size_t step=0;step<go.max_new_tokens;++step){const std::size_t begin=result.size()>go.max_context_tokens?result.size()-go.max_context_tokens:0;std::vector<bpe::TokenId> ctx(result.begin()+begin,result.end());Tensor logits({ctx.size(),o.vocabulary_size},w.token_embedding.dtype(),DeviceType::CPU);forward(logits,ctx,w,o,co,si);std::vector<float> host(logits.numel());logits.copy_to_host(host);std::vector<float> last(host.end()-o.vocabulary_size,host.end());auto next=sample(last,result,go,rng);result.push_back(next);if(go.eos_token_id&&next==*go.eos_token_id)break;}return result;}
TextGenerationResult generate_text_with_stats_cpu(const bpe::BpeTokenizer& tok,std::string_view prompt,const TransformerModelWeights& w,const Tensor& co,const Tensor& si,const TransformerModelOptions& o,const GenerationOptions& go){auto p=tok.encode(prompt);auto r=generate_tokens_cpu(p,w,co,si,o,go);return {tok.decode(r),p.size(),r.size()-p.size()};}
